### ISSUE TITLE
Maybe something useful / relevant

### ISSUE THREAD

**Issue by floris-vos** [bumatic/bitchute-scraper#4]
I'm a bit new to Github so sorry if this is the wrong way to do this, but I made a Bitchute Scraper as well, and just use a post request. Just 25 lines of code, and no extra libraries needed except Request, to get a json object of search results. Here it is:

```
import requests
from json import loads

url = "https://www.bitchute.com/api/search/list/"
search_query = "YOUR SEARCH QUERY"
headers = {
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
    "Host": "www.bitchute.com",
    "Origin": "https://www.bitchute.com",
    "Referer": f"https://www.bitchute.com/search/?query={search_query}",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
}
session = requests.Session()
response = session.get(f"https://www.bitchute.com/search/?query={search_query}")
index1 = response.text.index("csrf") + 28
csrf_token = response.text[index1:index1+64]

payload = {
    "query": search_query,
    "kind": "video",
    "csrfmiddlewaretoken": csrf_token,
}

response = session.post(url, headers=headers, data=payload).content.decode()
session.close()
```

**Comment by bumatic** [comment]
Thanks for the suggestions. Since this is not an issue with the scraper I'll close it. 

BTW: My understanding of "scrapers" expects a little more than retrieving raw html responses. And one could argue that your code doesn't even do that properly for bitchute: As far as I see proposed solution only retrieves the html containing the first 10 results for a query. If you use headless browser and programmatically scroll to the bottom until no more additional results are dynamically loaded, you get the entire results set. Once this is done your scraper should parse the data as well, i.e. scrape the relevant bits and pieces out of the website and save it as structured data. However, I might be wrong and your 25 lines do all that. :)

**Comment by floris-vos** [comment]
Understand. Yes, I thought I would just share it, in case it would be somhow useful. It is of course only very basic, and indeed, only provides 10 results. Might be possible to get more using the "page" parameter but not sure yet.
